import Head from "next/head";
// import Image from "next/image";
import styles from "../styles/Home.module.css";
import EventList from "../components/events/event-list";
import { getAllEvents, getFeaturedEvents } from "../dummy-data";

export default function Home() {
  const featuredList = getFeaturedEvents();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <EventList items={featuredList} />
      </main>
    </div>
  );
}

// https://heroicons.com
